spring:
  application:
    name: eureka
  config:
      import: 'optional:configserver:'
  cloud:
    config:
      uri: http://192.168.50.181:8071
      username: config
      fail-fast: true
      retry:
        multiplier: 1.1
        initial-interval: 1000
        max-attempts: 10
        max-interval: 2000

      