spring:
  application:
    name: eureka
  config:
      import: optional:configserver:http://config:8071
  cloud:
    config:
      fail-fast: true
      retry:
        multiplier: 1.1
        initial-interval: 1000
        max-attempts: 10
        max-interval: 2000
      
      